### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cehamot** [Tanibox/tania#15]
![selection_002](https://user-images.githubusercontent.com/15309823/28246752-6a6fdab6-6a4b-11e7-9227-76f86c797b34.png).

saat instalasi command "php composer.phar install" terjadi error. bisa membantu?

**Comment by wisn** [comment]
This issue is familiar with https://github.com/Tanibox/tania/issues/13
Please try to follow [this](https://github.com/Tanibox/tania/issues/13#issuecomment-314722369)

It's because you didn't setup `app/config/parameters.yml`

**Comment by cehamot** [comment]
oke thanks, this problem has solved. I have not changed the mailer with admin. 
![selection_003](https://user-images.githubusercontent.com/15309823/28246906-9d54d054-6a4f-11e7-99b3-6b22699393bd.png)

**Comment by cehamot** [comment]
Is there bahasa for tania app?

**Comment by raymerta** [comment]
you can contribute to provide one :D

**Comment by lynxluna** [comment]
And I suggest if you're opening entirely different thing, please open new issue ticket. 

I think @bepitulaz can close this one.
