### ISSUE TITLE
Broken Responsive Design on Firefox

### ISSUE THREAD

**Issue by wisn** [Tanibox/tania#18]
Here are some screen captures.

![screenshot from 2017-07-17 at 23 39 12](https://user-images.githubusercontent.com/8147926/28280018-9366ec46-6b4c-11e7-842f-64f3439f2665.png)
![screenshot from 2017-07-17 at 23 42 02](https://user-images.githubusercontent.com/8147926/28280019-93676d60-6b4c-11e7-860a-afcccc9e3753.png)
![screenshot from 2017-07-17 at 23 42 58](https://user-images.githubusercontent.com/8147926/28280020-937218f0-6b4c-11e7-922f-06c0aa52d4ee.png)
![screenshot from 2017-07-17 at 23 46 32](https://user-images.githubusercontent.com/8147926/28280022-94b38c94-6b4c-11e7-8855-688cd50be79b.png)

So, is this project possibly support for mobile? If is it not, then this is not a problem. The `dropdown menu` didn't work too.

**Comment by bepitulaz** [comment]
Hi @wisn,

When we started this project, we don't think mobile first design at all. But, we will try to elaborate more how is the best way to support the mobile device. We don't think the responsive design will give the best UX for this kind of data heavy web application.

Thanks.

**Comment by wisn** [comment]
I see. It's now all clear. You may close this issue if you wish.
