### ISSUE TITLE
Blank Maps when There is No Farm

### ISSUE THREAD

**Issue by wisn** [Tanibox/tania#19]
I think it's better to hide the maps instead of displaying a blank maps.

![screenshot from 2017-07-18 00-08-03](https://user-images.githubusercontent.com/8147926/28280331-9c884102-6b4d-11e7-81fd-b5048177dbb1.png)

**Comment by bepitulaz** [comment]
Let me mention @alcatrazia for this enhancement feedback. We can elaborate more about the UX. Thanks for your feedback.

**Comment by bepitulaz** [comment]
The enhancement had been implemented in this commit https://github.com/Tanibox/tania/commit/01dced4c71d81ad2608c8990ff27d3fde873df05. It will be released for v1.1.
