### ISSUE TITLE
Do i18n for every string in Tania.

### ISSUE THREAD

**Issue by bepitulaz** [Tanibox/tania#25]
I want to do internationalisation. So, we can accommodate users who can't understand English.

**Comment by lynxluna** [comment]
Just for reminder, we're using `xliff` format: https://en.wikipedia.org/wiki/XLIFF

**Comment by bepitulaz** [comment]
This commit https://github.com/Tanibox/tania/commit/bbece71c9b203770f4568cec72f83705cf1db871 is completing this enhancement. We can close this issue.
