### ISSUE TITLE
Moves the parameters.yml to environment variable.

### ISSUE THREAD

**Issue by lynxluna** [Tanibox/tania#39]
I think we can pick the environment variable changes from #38 at commit: https://github.com/Tanibox/tania/pull/38/commits/d381ee227be91d04f0635aa9e776e329f922b11f

This way, tania can pick settings from environment variables. Gonna cc @bepitulaz for this.

**Comment by bepitulaz** [comment]
Done by this commit https://github.com/Tanibox/tania/commit/6f40f101278cb9bc1f2334398721682b1e48d96c. Don't forget to check the `.env` example file here https://github.com/Tanibox/tania/blob/development/.env-example.
