### ISSUE TITLE
Security issue: Rename .env file to prevent credentials leak

### ISSUE THREAD

**Issue by rugk** [Tanibox/tania#43]
If the file is not manually properly secured, in production the file `.env` may be accessible by anyone by just visiting the site as `example.com/.env`. If that's the case, database and mail (SMTP, …) passwords may be exposed.

That's why you'd be better of by renaming it to `.env.php` (or similar) as the file is then parsed by every usual webserver and thus not displayed as plain-text when visiting the site.

BTW: Your website is down or not yet set up.

**Comment by ucay** [comment]
I think renaming `.env` to `.env.php` will be pain for developer with editor using autodetect language, linter or code fixer (e.g. php-cs-fixer).

But, +1 for not use `.env` in production. Already mentioned in [The Dotenv Component](https://symfony.com/doc/current/components/dotenv.html), better use "real" environment variables.
> Symfony Dotenv should only be used in development/testing/staging environments. For production environments, use "real" environment variables.

**Comment by rugk** [comment]
Or so… In any case keep them out from potentially accessible files.

**Comment by bepitulaz** [comment]
@rugk I put the `.env-example` file just for listing all the environment variables. Actually, in production, it will be better to use the real environment variables. Well, I should give a new condition here https://github.com/Tanibox/tania/blob/master/app/AppKernel.php to not load the `.env` file while it in production mode.

Btw, yes the gettania.org is down. We are attempting to migrate it to Github project page.
