### ISSUE TITLE
Docker instance login?

### ISSUE THREAD

**Issue by chrigui** [Tanibox/tania#59]
hello,
after few days i finally installed Tania using docker... but i cannot login.
i tried tania/taniapass
admin/admin
admin/taniapass
admin/tania and tania/admin

and when i try to signup i get an error:
http://138.68.xx.xxx/register/
am i missing something ?

**Comment by bepitulaz** [comment]
Hello @chrigui,

What did the error say? Your step was correct. After finishing the installation, you should register.

**Comment by chrigui** [comment]
hi @bepitulaz, thank you for tyour reply.
here is a screenshot:
<img width="1487" alt="screen shot 2017-11-23 at 11 01 57" src="https://user-images.githubusercontent.com/1286895/33163116-4e04ccbc-cfd9-11e7-8911-d745f5ca9680.png">

**Comment by bepitulaz** [comment]
Table `tania.users` doesn't exist means the database is not configured correctly. Have you run `php bin/console --no-interaction doctrine:migrations:migrate` command?

**Comment by chrigui** [comment]
i used docker... i though it was done automatically :(
i just typed the command and here is when i got:

php bin/console --no-interaction doctrine:migrations:migrate
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DOMDocument" from the global namespace.
Did you forget a "use" statement? in /tania/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php:52
Stack trace:
#0 /tania/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(368): Symfony\Component\Config\Util\XmlUtils::loadFile('/tania/vendor/s...', Array)
#1 /tania/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(41): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseFileToDOM('/tania/vendor/s...')
#2 /tania/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php(96): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->load('web.xml')
#3 /tania/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php(59): Symfony\Bundle\FrameworkBundle\DependencyInjection\Framewor in /tania/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php on line 52

**Comment by bepitulaz** [comment]
You should add the command inside your Dockerfile:
```
Run php bin/console --no-interaction doctrine:migrations:migrate
```
or you execute it from your shell to the running container, such as:
```
docker exec -it yourcontainer_name php bin/console --no-interaction doctrine:migrations:migrate
```
Hope it helps :)

**Comment by chrigui** [comment]
It worked!
thank you so, much @bepitulaz 👍

**Comment by chrigui** [comment]
Do you have an email please i would like to discuss something with you in private...

**Comment by bepitulaz** [comment]
@chrigui yes, please send your email to asep@tanibox.com. Btw, I will close this issue now :)
